baseURL = 'https://besh0y.com/'
languageCode = 'en-us'
title = 'Beshoy Danial'
theme = 'construction'

[params]
title = "BD"
message = "Beshoy Danial"
message2 = "Under Construction"
background = "bg.mov"

socialIcons = [
    {name = "email", url = "contact@besh0y.com"},
    {name = "github", url = "https://github.com/besh0y"},
    {name = "linkedin", url = "https://www.linkedin.com/in/besh0y"},
]

[caches]
[caches.images]
dir = ':cacheDir/images'